//
// Created by rafae on 3/1/2024.
//

#ifndef BINARY_DATA_PROCESSING_TYPEDEFINITIONS_HPP
#define BINARY_DATA_PROCESSING_TYPEDEFINITIONS_HPP

enum type{
    INT,
    UNSIGNED_INT,
    SHORT,
    UNSIGNED_SHORT,
    LONG,
    UNSIGNED_LONG,
    LONG_LONG,
    UNSIGNED_LONG_LONG,
    FLOAT,
    DOUBLE,
    LONG_DOUBLE,
    STRING,
    CHAR,
    UNSIGNED_CHAR,
    BOOL,
    INT_ARRAY,
    UNSIGNED_INT_ARRAY,
    SHORT_ARRAY,
    UNSIGNED_SHORT_ARRAY,
    LONG_ARRAY,
    UNSIGNED_LONG_ARRAY,
    LONG_LONG_ARRAY,
    UNSIGNED_LONG_LONG_ARRAY,
    FLOAT_ARRAY,
    DOUBLE_ARRAY,
    LONG_DOUBLE_ARRAY,
    STRING_ARRAY,
    CHAR_ARRAY,
    UNSIGNED_CHAR_ARRAY,
    BOOL_ARRAY,
};

enum system_type{
    LE,
    BE
};
#endif //BINARY_DATA_PROCESSING_TYPEDEFINITIONS_HPP
